#  Configuración del Proxy Host en NPM tras desplegar:
#        ===Details===
#        - Dominio  : pdf.mi-dominio.duckdns.org
#        - Scheme   : http
#        - Host     : stirling-pdf
#        - Port     : 8080
#        - Cache Assets:          DESACTIVADO
#        - Block Common Exploits: ACTIVADO
#        - Websockets Support:    ACTIVADO
#        ===SSL===
#        - SSL Certificate : *.tu-dominio.duckdns.org (wildcard existente)
#        - Force SSL       : ACTIVADO
#        - HTTP/2 Support  : ACTIVADO
#        - HSTS Enabled    : ACTIVADO
#        - HSTS Sub-domains: DESACTIVADO

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest-fat
    container_name: stirling-pdf
    restart: always
    ports:
      - "8080:8080"                    # Expone el puerto 8080 hacia la VM
    environment:
      - TZ=Europe/Madrid
      - LANGS=es_ES                    # Descarga fuentes y diccionarios OCR en español
      - SYSTEM_DEFAULTLOCALE=es-ES     # Configura la interfaz por defecto en español
      - DOCKER_ENABLE_SECURITY=false   # Desactivado (Cámbiado a true si quieres login obligatorio)
    volumes:
      - ./trainingData:/usr/share/tessdata
      - ./extraConfigs:/configs
      - ./logs:/logs
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true